@echo off
TITLE REPARADOR USB POR [TEMPLARIO] 
color 0B  



IF NOT EXIST CUARENTENA_JAC MD CUARENTENA_JAC

rem =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
rem                    Batch Logo Maker V1.0
rem  
rem  =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
rem  BATCH LOGO MAKER V1.0 . LICENCIA FRE-WARE
rem                             
rem          
mode con cols=41 lines=10
cls
echo.
echo.
echo      อ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      อ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
echo      บ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
echo      บ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
echo      บ
echo      ศ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
echo      บ
echo      ศ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
echo      บ
echo      ศผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
echo      บ
echo      ศผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
echo      บบ
echo      ศผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษ
echo      บบ
echo      ศผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษป
echo      บบ
echo      ศผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษป
echo      บบ
echo      ศผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอป
echo      บ บ
echo      ศอผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอป
echo      บ บ
echo      ศอผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออป
echo      บ  บ
echo      ศออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออป
echo      บ  บ
echo      ศออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออป
echo      บ R บ
echo      ศอออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออป
echo      บ RE บ
echo      ศออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออป
echo      บ REP บ
echo      ศอออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออป
echo      บ REPA บ
echo      ศออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออป
echo      บ REPAR บ
echo      ศอออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออป
echo      บ REPARA บ
echo      ศออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออป
echo      บ REPARAD บ
echo      ศอออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออป
echo      บ REPARADO บ
echo      ศออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออป
echo      บ REPARADOR บ
echo      ศอออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออออป
echo      บ REPARADOR  บ
echo      ศออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออออป
echo      บ REPARADOR U บ
echo      ศอออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออออออป
echo      บ REPARADOR US บ
echo      ศออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออออออป
echo      บ REPARADOR USB บ
echo      ศอออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออออออออป
echo      บ REPARADOR USB  บ
echo      ศออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออออออออป
echo      บ REPARADOR USB [ บ
echo      ศอออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออออออออออป
echo      บ REPARADOR USB [V บ
echo      ศออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออออออออออป
echo      บ REPARADOR USB [VE บ
echo      ศอออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออออออออออออป
echo      บ REPARADOR USB [VER บ
echo      ศออออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออออออออออออป
echo      บ REPARADOR USB [VERS บ
echo      ศอออออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออออออออออออออป
echo      บ REPARADOR USB [VERSI บ
echo      ศออออออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออออออออออออออป
echo      บ REPARADOR USB [VERSIO บ
echo      ศอออออออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออออออออออออออออป
echo      บ REPARADOR USB [VERSION บ
echo      ศออออออออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออออออออออออออออป
echo      บ REPARADOR USB [VERSION  บ
echo      ศอออออออออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออออออออออออออออออป
echo      บ REPARADOR USB [VERSION 2 บ
echo      ศออออออออออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออออออออออออออออออป
echo      บ REPARADOR USB [VERSION 2. บ
echo      ศอออออออออออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษออออออออออออออออออออออออออออป
echo      บ REPARADOR USB [VERSION 2.0 บ
echo      ศออออออออออออออออออออออออออออผ
ping -n 1,9 0.0.0.0 >nul
cls
echo.
echo.
echo      ษอออออออออออออออออออออออออออออป
echo      บ REPARADOR USB [VERSION 2.0] บ
echo      ศอออออออออออออออออออออออออออออผ
ping -n 1 Localhost > nul
cls
echo.
echo.
echo         ษอออออออออออออออออออออออป
echo         บ TEMPLARIO17          บ
echo         ศอออออออออออออออออออออออผ
echo MsgBox " APLICACION CREADA PARA ELIMINAR VIRUS USB!! " ,vbinformation ,"Creado por TEMPLARIO17" >msg.vbs
start msg.vbs
ping -n 2 0.0.0.0 > nul
del /F /q /s msg.vbs > nul
:SPAN
mode con cols=60 lines=15
cls
echo.
echo.
echo                ษอออออออออออออออออออออออออออออป
echo                บ REPARADOR USB [VERSION 2.0] บ
echo                ศอออออออออออออออออออออออออออออผ
echo.
echo.
echo.
echo.
ECHO           PULSA [ENTER] PARA INICIAR LA REPARACION
echo.
echo.
echo               [ HD TEMPLARIO17 ]
ECHO                      
pause > nul
CLS
ECHO  ==========================================================
ECHO                     INICIANDO REPARACION
PING -n 2 LOCALHOST>NUL
ECHO.
ECHO.
ECHO.
ECHO  ==========================================================
ECHO                      ESCANEANDO UNIDAD
ECHO.
IF EXIST *.LNK (
    ECHO VIRUS DETECTADOS:
    ECHO.
    FOR /F "TOKENS=*" %%A IN ('DIR /B *.LNK') DO ( ECHO %%A & PING -n 1,9 0.0.0.0 >NUL)
    PING -n 2 LOCALHOST>NUL
    ECHO.
    ECHO  ==========================================================
    ECHO                  ELIMINANDO LNKดS DETECTADOS
    FOR /F "TOKENS=*" %%B IN ('DIR /B *.LNK') DO ( ECHO ELIMINANDO: "%%B" & DEL /F /Q "%%B" & PING -n 1,9 0.0.0.0 >NUL)
) ELSE (
    ECHO.
    ECHO NO SE HA ENCONTRADO ACCESOS DIRECTOS
    PING -n 2 LOCALHOST>NUL
)

ECHO.
ECHO  ==========================================================
ECHO.
ECHO                     DESOCULTANDO ARCHIVOS
ECHO.
PING -n 1 LOCALHOST>NUL
FOR /F "TOKENS=*" %%C IN ('DIR /B /A:H') DO ( ECHO DESOCULTANDO: "%%C" & ATTRIB -S -H "%%C" 2>NUL)
FOR /F "TOKENS=*" %%D IN ('DIR /B /A:S') DO ( ECHO DESOCULTANDO: "%%D" & ATTRIB -S -H "%%D" 2>NUL)
ECHO.

if exist *.exe goto move
if exist *.dll goto move
if exist *.scr goto move
GOTO RECYCLER_USB

:move
ECHO.
ECHO  ==========================================================
ECHO.
ECHO               MOVIENDO EJECUTABLES A CUARENTENA            
ECHO.
PING -n 1 LOCALHOST>NUL
IF EXIST *.EXE FOR /F "TOKENS=*" %%E IN ('DIR /B *.EXE') DO ( ECHO MOVIENDO: "%%E" & MOVE /Y "%%E" CUARENTENA_JAC&PING -n 1,9 0.0.0.0>NUL)
IF EXIST *.DLL FOR /F "TOKENS=*" %%F IN ('DIR /B *.DLL') DO ( ECHO MOVIENDO: "%%F" & MOVE /Y "%%F" CUARENTENA_JAC&PING -n 1,9 0.0.0.0>NUL)
IF EXIST *.SCR FOR /F "TOKENS=*" %%G IN ('DIR /B *.SCR') DO ( ECHO MOVIENDO: "%%G" & MOVE /Y "%%G" CUARENTENA_JAC&PING -n 1,9 0.0.0.0>NUL)
IF EXIST *.PIF FOR /F "TOKENS=*" %%H IN ('DIR /B *.PIF') DO ( ECHO MOVIENDO: "%%H" & MOVE /Y "%%H" CUARENTENA_JAC&PING -n 1,9 0.0.0.0>NUL)
MOVE /Y *.EXE CUARENTENA_JAC 2> NUL
MOVE /Y *.DLL CUARENTENA_JAC 2> NUL
MOVE /Y *.SCR CUARENTENA_JAC 2> NUL
MOVE /Y *.PIF CUARENTENA_JAC 2> NUL

echo MsgBox "Reparador USB a movido los posibles virus a la carpeta de cuarentena" ,vbinformation ,"Creado por templario17" >msg.vbs
start msg.vbs
ping -n 2 LOCALHOST > nul
del /F /q /s msg.vbs > nul
ECHO.
:RECYCLER_USB
IF EXIST RECYCLER (
ECHO.
ECHO  ==========================================================
ECHO.
ECHO                 REMOVIENDO CARPETA RECYCLER
ECHO.
ECHO. PASO 1: QUITANDO PROTECCION DESKTOP
ECHO.
ATTRIB -R -S -H "RECYCLERDESKTOP.INI"
CD RECYCLER
ATTRIB -R -S -H /S /D
CD..
PING -n 1,9 0.0.0.0>NUL
ECHO.
ECHO. PASO 2: REMOVIENDO ARCHIVO DESKTOP
ECHO.
DEL /F /Q "RECYCLERDESKTOP.INI" 2> NUL
PING -n 1,9  0.0.0.0>NUL
ECHO.
ECHO. PASO 3: REMOVIENDO SPAM DE RECYCLER
ECHO.
DEL /F /Q /S "RECYCLER"
PING -n 1,9 0.0.0.0>NUL
ECHO.
ECHO. PASO 4: QUITANDO CARPETA RECYCLER
ECHO.
RD /S /Q RECYCLER
PING -n 1,9 0.0.0.0>NUL
ECHO.
ECHO                    PROCESO FINALIZADO
PING -n 2 LOCALHOST>NUL
)


:end
echo MsgBox " Tu USB a sido reparada " ,vbinformation ,"Creado por TEMPLARIO17" >msg.vbs
start msg.vbs
ping -n 2 LOCALHOST > nul
del /F /q /s msg.vbs > nul
echo MsgBox " CONTACTATO:  @D_Andres " ,vbinformation ,"Creado por Templario17" >msg.vbs
start msg.vbs
ping -n 2 0.0.0.0 > nul
del /F /q /s msg.vbs > nul


cls
echo.
echo.
echo                ษอออออออออออออออออออออออออออออป
echo                บ REPARADOR USB [VERSION 2.0] บ
echo                ศอออออออออออออออออออออออออออออผ
echo.
echo.
echo.                  REPARACION FINALIZADA!!
echo.
ECHO            PULSA [ENTER] PARA CERRAR ESTA VENTANA
echo.
echo.
echo               [ TEMPLARIO17]
ECHO                      
pause > nul 